{% set name = "epitools" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/epitools-{{ version }}.tar.gz
  sha256: 77e97b6902ada7cb348acec1ebf36c850e1c25100332f4c95ef3166a61377f4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - partseg
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - python >=3.9
    - scikit-image >=0.20
    - scipy

test:
  imports:
    - epitools
    - epitools.main
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/epitools/epitools
  summary: EpiTools Plugin
  license: BSD-3-Clause
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - giuliapaci
    - goanpeca
    - jaimergp
    - Pablo1990
