{% set name = "epitools" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/epitools-{{ version }}.tar.gz
  sha256: cae74fded34d12543459732d873dc144086c8528c150552d06577839737c30c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - partseg
    - magicgui
    - matplotlib-base
    - napari
    - networkx  # Not declared but used in source code
    - numpy
    - pandas
    - python >=3.9
    - scikit-image >=0.20
    - scipy

test:
  imports:
    - epitools
    - epitools.main
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/epitools
  summary: Extract the membrane signal from epithelial tissues and analyze it with computer vision
  license: BSD-3-Clause
  license_file: LICENCE.md
  dev_url: https://github.com/epitools/epitools

extra:
  recipe-maintainers:
    - giuliapaci
    - goanpeca
    - jaimergp
    - Pablo1990
